name: Build
on:
  push:
    branches-ignore:
      - 'master'
      - 'releases/**'
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  pull_request:
    branches-ignore:
      - 'master'
      - 'releases/**'
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  workflow_dispatch:
jobs:
  analyze_test:
    name: Analyze Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
          # cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-${{ hashFiles('code/pubspec.lock') }}
        env:
          cache-name: flutter-cache
      - name: Flutter Version
        run: flutter --version
      - name: Pub Get
        run: flutter pub get
      - name: Analyze Code
        continue-on-error: true
        run: |
          flutter analyze || echo passed
      - name: Test
        run: flutter test
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [analyze_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
          # cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-${{ hashFiles('code/pubspec.lock') }}
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --debug

  #  Need Podfile to configure IOS version to build success
  build_ios:
    name: Build IOS
    runs-on: macos-latest
    needs: [analyze_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-macos-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
          # cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-${{ hashFiles('code/pubspec.lock') }}
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Build IPA
        run: flutter build ios --release --no-codesign
