name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
jobs:
  remote_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v3
        with:
          repository: FA-Super-Team/fa_master
          token: ${{ secrets.TOKEN }}
          path: '.'
      - run: ls -la
