name: Flutter Release
on:
  workflow_dispatch:
jobs:
  remote_check:
    name: Remote Check
    runs-on: ubuntu-latest
    steps:
      - run: echo OK
      # Download release build then add additional info for publishing