name: Flutter Preview Android (TA)
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        description: The repo which dev ops work in
      ref_name:
        type: string
        required: true
        description: The ref name of repo which dev ops work in
      ref:
        type: string
        required: true
        description: The ref of repo which dev ops work in
jobs:
  remote_check_ta:
    name: Remote Check ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Flutter Version
        run: flutter --version
      - name: Pub Get
        run: flutter pub get
      - name: Analyze Code
        continue-on-error: true
        run: |
          flutter analyze || echo passed
      - name: Test
        run: flutter test
  build_android_debug_ta:
    name: Build Preview APK Android Debug (TA) ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check_ta]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Pub Get Rename Package
        run: flutter pub global activate rename
      - name: Rename App
        run: flutter pub global run rename --appname "FA Master DTA"
      - name: Build APK
        run: flutter build apk --debug --build-name=${{ github.run_number }}.0.0-preview-debug --build-number=${{ github.run_number }} --dart-define=ENV=DEV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-${{ github.event.inputs.ref_name }}-preview-apk-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/flutter-apk/*.apk
  build_android_dev_ta:
    name: Build Preview APK Android Dev (TA) ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check_ta]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Pub Get Rename Package
        run: flutter pub global activate rename
      - name: Rename App
        run: flutter pub global run rename --appname "FA Master PDTA"
      - name: Build APK
        run: flutter build apk --build-name=${{ github.run_number }}.0.0-preview-dev --build-number=${{ github.run_number }} --dart-define=ENV=DEV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev-${{ github.event.inputs.ref_name }}-preview-apk-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/apk/release/*.apk
  build_android_prod_ta:
    name: Build Preview APK Android Prod (TA) ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check_ta]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Pub Get Rename Package
        run: flutter pub global activate rename
      - name: Rename App
        run: flutter pub global run rename --appname "FA Master PPTA"
      - name: Build APK
        run: flutter build apk --build-name=${{ github.run_number }}.0.0-preview --build-number=${{ github.run_number }} --dart-define=ENV=PROD
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prod-${{ github.event.inputs.ref_name }}-preview-apk-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/apk/release/*.apk
  build_splited_android_dev_ta:
    name: Build Preview Splited APKs Android Dev (TA) ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check_ta]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Pub Get Rename Package
        run: flutter pub global activate rename
      - name: Rename App
        run: flutter pub global run rename --appname "FA Master PDTA"
      - name: Build Splited APKs
        run: flutter build apk --split-per-abi --build-name=${{ github.run_number }}.0.0-preview-dev --build-number=${{ github.run_number }} --dart-define=ENV=DEV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev-${{ github.event.inputs.ref_name }}-splited-preview-apks-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/apk/release/*.apk
  build_splited_android_prod_ta:
    name: Build Preview Splited APKs Android Prod (TA) ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check_ta]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Pub Get Rename Package
        run: flutter pub global activate rename
      - name: Rename App
        run: flutter pub global run rename --appname "FA Master PPTA"
      - name: Build Splited APKs
        run: flutter build apk --split-per-abi --build-name=${{ github.run_number }}.0.0-preview --build-number=${{ github.run_number }} --dart-define=ENV=PROD
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prod-${{ github.event.inputs.ref_name }}-splited-preview-apks-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/apk/release/*.apk