name: Flutter Release Android
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        description: The repo which dev ops work in
      ref_name:
        type: string
        required: true
        description: The ref name of repo which dev ops work in
      ref:
        type: string
        required: true
        description: The ref of repo which dev ops work in
jobs:
  remote_check:
    name: Remote Check ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Flutter Version
        run: flutter --version
      - name: Pub Get
        run: flutter pub get
      - name: Analyze Code
        continue-on-error: true
        run: |
          flutter analyze || echo passed
      - name: Test
        run: flutter test
  build_appbundle:
    name: Build Release AAB Android ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Build APK
        run: flutter build appbundle --dart-define=ENV=PROD
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-appbundle-${{ github.event.inputs.ref_name }}-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/apk/release/*.aab
  build_android:
    name: Build Release APK Android ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --dart-define=ENV=PROD
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk-${{ github.event.inputs.ref_name }}-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/flutter-apk/*release*.apk
  build_splited_android:
    name: Build Release Splited APK Android ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    needs: [remote_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Build Splited APKs
        run: flutter build apk --split-per-abi --dart-define=ENV=PROD
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: splited-release-apks-${{ github.event.inputs.ref_name }}-v${{ github.run_number }}-no.${{ github.run_id }}
          path: build/app/outputs/flutter-apk/*release*.apk
