name: Flutter Build IOS
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        description: The repo which dev ops work in
      ref_name:
        type: string
        required: true
        description: The ref name of repo which dev ops work in
      ref:
        type: string
        required: true
        description: The ref of repo which dev ops work in
jobs:
  remote_check:
    name: Remote Check ${{ github.event.inputs.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Flutter Version
        run: flutter --version
      - name: Pub Get
        run: flutter pub get
      - name: Analyze Code
        continue-on-error: true
        run: |
          flutter analyze || echo passed
      - name: Test
        run: flutter test
  build_ios:
    name: Build IOS ${{ github.event.inputs.ref_name }}
    runs-on: macos-latest
    needs: [remote_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.TOKEN }}
          path: '.'
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
          cache: true
          cache-key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}
          cache-path: ${{ runner.tool_cache }}/flutter
        env:
          cache-name: flutter-cache
      - name: Pub Get
        run: flutter pub get
      - name: Pub Get Rename Package
        run: flutter pub global activate rename
      - name: Rename App
        run: flutter pub global run rename --appname "FA Master D"
      - name: Build IPA
        run: flutter build ios --release --no-codesign
